name: Build Windows Python Wheels

on:
  push:
    branches: [main, master]
    #tags: ["v*"]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on Windows
    runs-on: windows-2019  # Using 2019 for VS 2017 compatibility
    timeout-minutes: 120   # Set a 2-hour timeout for the entire job
    strategy:
      matrix:
        python:
          - {version: "3.8", major: 3, minor: 8}
          - {version: "3.9", major: 3, minor: 9}
          - {version: "3.10", major: 3, minor: 10}
          - {version: "3.11", major: 3, minor: 11}
          - {version: "3.12", major: 3, minor: 12}
        architecture: [x64]  # Removed x86, only building for x64

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python.version }}
          architecture: ${{ matrix.architecture }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel setuptools

      - name: Setup NASM
        run: |
          choco install nasm -y
          echo "C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Setup Strawberry Perl
        run: |
          # Check if Perl is already installed and locate it
          $perlCmd = Get-Command perl -ErrorAction SilentlyContinue
          Write-Host "Perl found at: $($perlCmd.Source)"
          
          # Install Strawberry Perl if not found
          if (-not $perlCmd) {
            choco install strawberryperl -y
            $perlCmd = Get-Command perl -ErrorAction SilentlyContinue
            Write-Host "Installed Perl at: $($perlCmd.Source)"
          }
          
          # Create C:\Perl64 directory and copy or symlink Perl there
          if (-not (Test-Path "C:\Perl64")) {
            Write-Host "Creating C:\Perl64 directory"
            # Extract the parent directory of perl.exe
            $perlDir = Split-Path -Parent (Split-Path -Parent $perlCmd.Source)
            Write-Host "Perl directory: $perlDir"
            
            # Create directory and copy Perl there (symlinks might not work well in this context)
            New-Item -Path "C:\Perl64" -ItemType Directory -Force
            Copy-Item -Path "$perlDir\*" -Destination "C:\Perl64" -Recurse -Force
          }
          
          # Verify Perl installation
          if (Test-Path "C:\Perl64\bin\perl.exe") {
            Write-Host "Perl successfully installed at C:\Perl64\bin\perl.exe"
          } else {
            Write-Host "Failed to setup Perl at C:\Perl64\bin\perl.exe"
            exit 1
          }

      - name: Install Cygwin
        run: |
          # Download Cygwin installer
          Invoke-WebRequest -Uri "https://cygwin.com/setup-x86_64.exe" -OutFile "C:\cygwin-setup.exe"
          
          # Install Cygwin and required packages
          Start-Process -FilePath "C:\cygwin-setup.exe" -ArgumentList "--quiet-mode --no-shortcuts --no-startmenu --no-desktop --only-site --root=C:\cygwin64 --site=http://cygwin.mirror.constant.com --packages=automake,binutils,bison,flex,libtool,make,gcc-core,bash" -Wait
          
          # Verify Cygwin installation
          if (Test-Path "C:\cygwin64\bin\bash.exe") {
            Write-Host "Cygwin successfully installed"
          } else {
            Write-Host "Failed to install Cygwin"
            exit 1
          }

      - name: Install 7-Zip
        run: |
          choco install 7zip -y

      - name: Setup Visual Studio Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.architecture }}
          toolset: 14.16  # Visual Studio 2017 (v141)

      - name: Prepare config.vc
        run: |
          Copy-Item -Path "project\build\config.vc.dist" -Destination "project\build\config.vc"
          $content = Get-Content -Path "project\build\config.vc"
          $content = $content -replace "PYTHON_VER_MAJOR=\d+", "PYTHON_VER_MAJOR=${{ matrix.python.major }}"
          $content = $content -replace "PYTHON_VER_MINOR=\d+", "PYTHON_VER_MINOR=${{ matrix.python.minor }}"
          Set-Content -Path "project\build\config.vc" -Value $content

      - name: Create expected directory structure
        run: |
          # Create expected directory structure for the build
          $repoPath = (Get-Location).Path
          Write-Host "Current repository path: $repoPath"
          
          # Create a symbolic link to ensure c:\librets points to the current checkout
          if (-not (Test-Path "c:\librets")) {
            New-Item -Path "c:\librets" -ItemType SymbolicLink -Value $repoPath -Force
          }

      # Fix Expat solution for x64 support
      - name: Fix Expat solution for x64
        run: |
          cd c:\librets\vendorsrc\expat\current\expat
          
          # List available solutions and configurations
          Write-Host "Available solution configurations:"
          $solutionFile = "expat.sln"
          $vcxprojFiles = Get-ChildItem -Filter "*.vcxproj"
          
          # Add x64 platform to each project
          foreach ($proj in $vcxprojFiles) {
            Write-Host "Adding x64 platform to $($proj.Name)"
            # Load the project file
            $xmlContent = [xml](Get-Content $proj.FullName)
            $ns = new-object System.Xml.XmlNamespaceManager($xmlContent.NameTable)
            $ns.AddNamespace("ns", "http://schemas.microsoft.com/developer/msbuild/2003")
            
            # Check if x64 platform exists
            $platformNode = $xmlContent.SelectSingleNode("//ns:PropertyGroup[contains(@Condition, 'x64')]", $ns)
            if (-not $platformNode) {
              Write-Host "x64 platform not found, adding it"
              
              # Find a Win32 node to clone
              $win32Node = $xmlContent.SelectSingleNode("//ns:PropertyGroup[contains(@Condition, 'Win32')]", $ns)
              if ($win32Node) {
                $newNode = $win32Node.CloneNode($true)
                $newNode.Attributes["Condition"].Value = $win32Node.Attributes["Condition"].Value.Replace("Win32", "x64")
                $win32Node.ParentNode.AppendChild($newNode)
                
                # Save the modified project
                $xmlContent.Save($proj.FullName)
                Write-Host "Added x64 platform to $($proj.Name)"
              }
            } else {
              Write-Host "x64 platform already exists in $($proj.Name)"
            }
          }
          
          # Use DevEnv to upgrade the solution
          & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.exe" /upgradeproject $solutionFile /projectconfig Release 2>&1
          
          # Attempt to build with the Win32 platform as a fallback
          cd c:\librets\vendorsrc
          Write-Host "Building expat with Win32 platform as fallback"
          nmake /f Makefile.vc TARGET_CPU=x86 build-expat
          
          # Copy Win32 binaries to x64 location
          mkdir -p "c:\librets\vendor\vs2017-x64\lib" -Force
          mkdir -p "c:\librets\vendor\vs2017-x64\include" -Force
          Copy-Item "c:\librets\vendor\vs2017-x86\lib\*" "c:\librets\vendor\vs2017-x64\lib\" -Force
          Copy-Item "c:\librets\vendor\vs2017-x86\include\*" "c:\librets\vendor\vs2017-x64\include\" -Force

      - name: Build vendor dependencies
        run: |
          cd vendorsrc
          powershell -ExecutionPolicy Bypass -File vendor.ps1
          nmake /f Makefile.vc TARGET_CPU=${{ matrix.architecture }} build-all

      - name: Build libRETS
        run: |
          nmake /f Makefile.vc TARGET_CPU=${{ matrix.architecture }} all
          nmake /f Makefile.vc TARGET_CPU=${{ matrix.architecture }} swig

      - name: Build Python wheel
        run: |
          cd project\swig\python
          python setup.py bdist_wheel

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: librets-py${{ matrix.python.version }}-${{ matrix.architecture }}-wheel
          path: project\swig\python\dist\*.whl
          retention-days: 7

  release-wheels:
    name: Release wheels to PyPI
    needs: build_wheels
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install twine

      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          pattern: librets-py*-wheel
          path: dist
          merge-multiple: true

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m twine upload dist/*.whl 
